swagger: "2.0"
info:
  version: "1.0.0"
  title: "Tempel des Schreckens API"
host: "petstore.swagger.io"
basePath: "/v2"

schemes:
- "https"
- "http"

paths:
  /start:
    post:
      parameters:
      - in: "body"
        name: "body"
        description: "Start a Tempel des Schreckens game"
        required: true
        schema:
          type: object
          properties:
            amountOfPlayers:
              type: integer
      responses:
        '200':
          description: Created

  /join:
    post:
      parameters:
      - in: "body"
        name: "body"
        description: "Join a room"
        required: true
        schema:
          type: object
          properties:
            secretToken:
              type: string
      responses:
        '200':
          description: "Successful"
          schema:
            type: object
            properties:
              guardian:
                type: boolean
              playerIds:
                type: array
                items:
                  type: "string"

  /my-rooms/{secretToken}:
    get:
      parameters:
      - in: "path"
        name: secretToken
        type: string
        required: true
      responses:
        '200':
          description: "Get your rooms"
          schema:
            type: object
            properties:
              rooms:
                type: array
                items:
                  type: "string"
                  enum: ["empty", "treasure", "trap"]

  /open:
    post:
      parameters:
      - in: "body"
        name: "body"
        description: "Join a room"
        required: true
        schema:
          type: object
          properties:
            secretToken:
              type: string
            targetPlayerId:
              type: integer
      responses:
        '200':
          description: "Successful"
